services:
  - type: web
    name: navin-developer-construction
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CONTACT_PHONE1
        sync: false
      - key: CONTACT_PHONE1_DISPLAY
        sync: false
      - key: CONTACT_PHONE2
        sync: false
      - key: CONTACT_PHONE2_DISPLAY
        sync: false
      - key: CONTACT_INSTAGRAM
        sync: false
